name: Deploy Card Detection App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  FLASK_ENV: production
  ENV: production

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test environment setup
      run: |
        python -c "
        import os
        from app import load_environment_secrets
        api_key = load_environment_secrets()
        if api_key:
            print('✅ API key loaded successfully')
        else:
            print('❌ API key not found')
            exit(1)
        "
    
    - name: Test imports
      run: |
        python -c "
        from ocr import LLMProcessor
        from app import app
        print('✅ All imports successful')
        "

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run application test
      run: |
        python -c "
        from app import app
        print('✅ Flask app initialized successfully')
        "
    
    # Add deployment steps here for your hosting platform
    # Examples:
    # - Deploy to Heroku
    # - Deploy to Railway
    # - Deploy to Vercel
    # - Deploy to AWS/GCP/Azure